#include <stdio.h>
#include <stdlib.h>
#include <time.h>
int a[9][9]={0},count[9]={0},numbers[9]={1,2,3,4,5,6,7,8,9};
int randoms(){
    int num = (rand() % (9 - 1 + 1)) + 1;
    return num;
}
void arrangeblockwise(){
    int n,i,j;
    for(i=0;i<3;i++){
        for(j=0;j<3;j++){
            while(1){
                n=randoms();
                if(count[n-1]<1){
                    count[n-1]++;
                    break;
                }
            }
            a[i][j]=n;
        }
    }
    for(i=0;i<3;i++){
        for(j=3;j<6;j++){
            while(1){
                n=randoms();
                if(count[n-1]<2){
                    count[n-1]++;
                    break;
                }
            }
            a[i][j]=n;
        }
    }
    for(i=0;i<3;i++){
        for(j=6;j<9;j++){
            while(1){
                n=randoms();
                if(count[n-1]<3){
                    count[n-1]++;
                    break;
                }
            }
            a[i][j]=n;
        }
    }
    for(i=3;i<6;i++){
        for(j=0;j<3;j++){
            while(1){
                n=randoms();
                if(count[n-1]<4){
                    count[n-1]++;
                    break;
                }
            }
            a[i][j]=n;
        }
    }
    for(i=6;i<9;i++){
        for(j=0;j<3;j++){
            while(1){
                n=randoms();
                if(count[n-1]<5){
                    count[n-1]++;
                    break;
                }
            }
            a[i][j]=n;
        }
    }
    for(i=3;i<6;i++){
        for(j=3;j<6;j++){
            while(1){
                n=randoms();
                if(count[n-1]<6){
                    count[n-1]++;
                    break;
                }
            }
            a[i][j]=n;
        }
    }
    for(i=3;i<6;i++){
        for(j=6;j<9;j++){
            while(1){
                n=randoms();
                if(count[n-1]<7){
                    count[n-1]++;
                    break;
                }
            }
            a[i][j]=n;
        }
    }
    for(i=6;i<9;i++){
        for(j=3;j<6;j++){
            while(1){
                n=randoms();
                if(count[n-1]<8){
                    count[n-1]++;
                    break;
                }
            }
            a[i][j]=n;
        }
    }
    for(i=6;i<9;i++){
        for(j=6;j<9;j++){
            while(1){
                n=randoms();
                if(count[n-1]<9){
                    count[n-1]++;
                    break;
                }
            }
            a[i][j]=n;
        }
    }
}
void arrangerowwise(){
    int p=8,i=0,j,k,l,temp;
    while(p--){
        for(j=0;j<9;j++)
            count[j]=0;
        for(j=0;j<9;j++){
            count[a[i][j]-1]++;
        }
        for(j=0;j<3;j++){
            if(count[(a[i][j])-1]>1){
                for(k=i+1;k<((i/3)*3)+3;k++){
                    for(l=0;l<3;l++){
                        if(count[(a[k][l])-1]==0){
                            temp=a[k][l];
                            a[k][l]=a[i][j];
                            a[i][j]=temp;
                            count[(a[k][l])-1]--;
                            count[(a[i][j])-1]++;
                        }
                    }
                }
            }
        }
        for(j=3;j<6;j++){
            if(count[(a[i][j])-1]>1){
                for(k=i+1;k<((i/3)*3)+3;k++){
                    for(l=3;l<6;l++){
                        if(count[(a[k][l])-1]==0){
                            temp=a[k][l];
                            a[k][l]=a[i][j];
                            a[i][j]=temp;
                            count[(a[k][l])-1]--;
                            count[(a[i][j])-1]++;
                        }
                    }
                }
            }
        }
        for(j=6;j<9;j++){
            if(count[(a[i][j])-1]>1){
                for(k=i+1;k<((i/3)*3)+3;k++){
                    for(l=6;l<9;l++){
                        if(count[(a[k][l])-1]==0){
                            temp=a[k][l];
                            a[k][l]=a[i][j];
                            a[i][j]=temp;
                            count[(a[k][l])-1]--;
                            count[(a[i][j])-1]++;
                        }
                    }
                }
            }
        }

        i++;
    }
}
void arrangecolwise(){
    int p=8,i=0,j,k,l,temp;
    while(p--){
        for(j=0;j<9;j++)
            count[j]=0;
        for(j=0;j<9;j++){
            count[a[j][i]-1]++;
        }
        for(j=0;j<3;j++){
            if(count[(a[j][i])-1]>1){
                for(k=i+1;k<((i/3)*3)+3;k++){
                        if(count[(a[j][k])-1]==0){
                            temp=a[j][k];
                            a[j][k]=a[j][i];
                            a[j][i]=temp;
                            count[(a[j][k])-1]--;
                            count[(a[j][i])-1]++;
                        }
                }
            }
        }
        for(j=0;j<3;j++){
            if(count[(a[j][i])-1]>1){
                for(k=i+1;k<((i/3)*3)+3;k++){
                        if(count[(a[j][k])-1]==0){
                            temp=a[j][k];
                            a[j][k]=a[j][i];
                            a[j][i]=temp;
                            count[(a[j][k])-1]--;
                            count[(a[j][i])-1]++;
                        }
                }
            }
        }
        for(j=0;j<3;j++){
            if(count[(a[j][i])-1]>1){
                for(k=i+1;k<((i/3)*3)+3;k++){
                        if(count[(a[j][k])-1]==0){
                            temp=a[j][k];
                            a[j][k]=a[j][i];
                            a[j][i]=temp;
                            count[(a[j][k])-1]--;
                            count[(a[j][i])-1]++;
                        }
                }
            }
        }
        i++;
    }
}
void sudokucheck(){
    int i,j,k,l,m,n;
    for(i=0;i<9;i++){
        for(j=0;j<9;j++){
            for(k=0;k<9;k++){
                if(a[i][j]==a[i][k]&&j!=k){
                    printf("dherbaalerrow\n");
                    return;
                }
            }
            for(k=0;k<9;k++){
                if(a[i][j]==a[k][j]&&i!=k){
                    printf("dherbaalercolumn\n");
                    return;
                }
            }
            for(k=(i/3)*3;k<((i/3)*3)+3;k++){
                for(l=(j/3)*3;l<((j/3)*3)+3;l++){
                    if(a[i][j]==a[k][l]&&i!=k&&j!=l){
                        printf("dherbaalerblock\n");
                        return;
                    }
                }
            }
        }
    }
    printf("shuvroboss\n");
    return;
}
int main(){
    int i=0,j,p=8,k,l,temp;
    arrangeblockwise();
    arrangerowwise();
    arrangecolwise();
    sudokucheck();
    for(i=0;i<9;i++){
        for(j=0;j<9;j++){
            printf("%d\t",a[i][j]);
        }
        printf("\n");
    }
    return 0;
}
